// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CreateEmployee() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"grid gap-4\"><div class=\"flex flex-col w-full max-w-sm gap-2\"><div class=\"flex flex-col gap-1\"><label for=\"name\" class=\"text-sm font-medium text-gray-700 flex items-center gap-2\"><div class=\"\"><span class=\"text-red-500 align-middle\">*</span> <span>名前</span> <span id=\"name-error\" class=\"text-red-500 text-xs\" data-text=\"$employeeCreate.errs.name\"></span></div></label> <input type=\"text\" id=\"name\" placeholder=\"名前\" required aria-live=\"polite\" aria-describedby=\"name-error\" data-bind=\"employeeCreate.name\" data-on-keydown__debounce.500ms=\"@post('/employees/validate?mode=create')\" class=\"w-full px-2 py-1 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\"></div><div class=\"flex flex-col gap-1\"><label for=\"email\" class=\"text-sm font-medium text-gray-700 flex items-center gap-2\"><div class=\"\"><span class=\"text-red-500 align-middle\">*</span> <span>メールアドレス</span> <span id=\"email-error\" class=\"text-red-500 text-xs\" data-text=\"$employeeCreate.errs.email\"></span></div></label> <input type=\"email\" id=\"email\" placeholder=\"メールアドレス\" required aria-live=\"polite\" aria-describedby=\"email-error\" data-bind=\"employeeCreate.email\" data-on-keydown__debounce.500ms=\"@post('/employees/validate?mode=create')\" class=\"w-full px-2 py-1 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\"></div></div><div class=\"grid gap-2 grid-cols-[12rem_12rem]\"><button type=\"button\" data-attr-disabled=\"!$employeeCreate.disabled\" data-on-click=\"@post('/employees/create')\" class=\" py-1.5 px-4 bg-primary text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed\">保存</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
