// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg *CreateEmployeeParams) (*Employee, error)
	DeleteEmployee(ctx context.Context, id int32) error
	GetEmployeeByID(ctx context.Context, id int32) (*Employee, error)
	GetEmployees(ctx context.Context) ([]*Employee, error)
	UpdateEmployee(ctx context.Context, arg *UpdateEmployeeParams) (*Employee, error)
}

var _ Querier = (*Queries)(nil)
